# Generated by Django 2.2.11 on 2020-03-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assign4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REF_DATE', models.CharField(max_length=20)),
                ('GEO', models.CharField(max_length=100)),
                ('DGUID', models.CharField(max_length=100)),
                ('Sex', models.CharField(max_length=100)),
                ('Agegroup', models.CharField(max_length=100)),
                ('Studentresponse', models.CharField(max_length=100)),
                ('UOM', models.CharField(max_length=100)),
                ('UOM_ID', models.CharField(max_length=100)),
                ('SCALAR_FACTOR', models.CharField(max_length=100)),
                ('SCALAR_ID', models.CharField(max_length=100)),
                ('VECTOR', models.CharField(max_length=100)),
                ('COORDINATE', models.CharField(max_length=100)),
                ('VALUE', models.CharField(max_length=100)),
                ('STATUS', models.CharField(max_length=100)),
                ('SYMBOL', models.CharField(max_length=100)),
                ('TERMINATED', models.CharField(max_length=100)),
                ('DECIMALS', models.CharField(max_length=100)),
            ],
        ),
    ]
